apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: temporal-rules
  namespace: monitoring
spec:
  groups:
  - name: temporal-metrics
    rules:
    - alert: TemporalRequestLatencyHigh
      annotations:
        description: Temporal {{ $labels.operation }} request latency is currently {{ $value | humanize }}, outside of SLO 150ms.
        summary: Temporal request latency is too high.
      expr: |
        histogram_quantile(0.95, sum by (le, operation) (rate(temporal_request_latency_bucket{job="benchmark-monitoring",operation="StartWorkflowExecution"}[5m])))
        > 0.150
      for: 5m
      labels:
        namespace: temporal
        severity: critical
    - alert: TemporalWorkflowTaskScheduleToStartLatencyHigh
      annotations:
        description: Temporal Workflow Task Schedule to Start latency is currently {{ $value | humanize }}, outside of SLO 150ms.
        summary: Temporal Workflow Task Schedule to Start latency is too high.
      expr: |
        histogram_quantile(0.95, sum by (le) (rate(temporal_workflow_task_schedule_to_start_latency_bucket{namespace="default"}[5m])))
        > 0.150
      for: 5m
      labels:
        namespace: temporal
        severity: critical
    - alert: TemporalActivityScheduleToStartLatencyHigh
      annotations:
        description: Temporal Activity Schedule to Start latency is currently {{ $value | humanize }}, outside of SLO 150ms.
        summary: Temporal Activity Schedule to Start latency is too high.
      expr: |
        histogram_quantile(0.95, sum by (le) (rate(temporal_activity_schedule_to_start_latency_bucket{namespace="default"}[5m])))
        > 0.150
      for: 5m
      labels:
        namespace: temporal
        severity: critical
