apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-matching
  labels:
    app.kubernetes.io/component: matching
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.20.3
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: matching
      app.kubernetes.io/instance: temporal
      app.kubernetes.io/name: temporal
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: matching
        app.kubernetes.io/instance: temporal
        app.kubernetes.io/name: temporal
        app.kubernetes.io/part-of: temporal
        app.kubernetes.io/version: 1.20.3
    spec:
      containers:
      - env:
        - name: BIND_ON_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICES
          value: matching
        - name: PROMETHEUS_ENDPOINT
          value: 0.0.0.0:8000
        - name: DYNAMIC_CONFIG_FILE_PATH
          value: /etc/temporal/dynamic_config/dynamic_config.yaml
        envFrom:
        - configMapRef:
            name: temporal-env
        image: temporalio/server:1.20.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 150
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: rpc
          timeoutSeconds: 1
        name: temporal
        ports:
        - name: rpc
          containerPort: 7235
          protocol: TCP
        - name: metrics
          containerPort: 8000
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/temporal/dynamic_config
          name: dynamic-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: dynamic_config.yaml
            path: dynamic_config.yaml
          name: temporal-dynamic-config
        name: dynamic-config